package dao;

import entity.Checklist;
import entity.ChecklistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChecklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    long countByExample(ChecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int deleteByExample(ChecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int insert(Checklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int insertSelective(Checklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    List<Checklist> selectByExample(ChecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    Checklist selectByPrimaryKey(String id);
    List<Checklist> selectByFKey(String mid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Checklist record, @Param("example") ChecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Checklist record, @Param("example") ChecklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Checklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKLIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Checklist record);
}