package entity;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MNAME
     *
     * @mbg.generated
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMAIL
     *
     * @mbg.generated
     */
    private String memail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MPASSWORD
     *
     * @mbg.generated
     */
    private String mpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated
     */
    public Member(String id, String mname, String memail, String mpassword) {
        this.id = id;
        this.mname = mname;
        this.memail = memail;
        this.mpassword = mpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated
     */
    public Member() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.ID
     *
     * @return the value of MEMBER.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.ID
     *
     * @param id the value for MEMBER.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MNAME
     *
     * @return the value of MEMBER.MNAME
     *
     * @mbg.generated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MNAME
     *
     * @param mname the value for MEMBER.MNAME
     *
     * @mbg.generated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMAIL
     *
     * @return the value of MEMBER.MEMAIL
     *
     * @mbg.generated
     */
    public String getMemail() {
        return memail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMAIL
     *
     * @param memail the value for MEMBER.MEMAIL
     *
     * @mbg.generated
     */
    public void setMemail(String memail) {
        this.memail = memail == null ? null : memail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MPASSWORD
     *
     * @return the value of MEMBER.MPASSWORD
     *
     * @mbg.generated
     */
    public String getMpassword() {
        return mpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MPASSWORD
     *
     * @param mpassword the value for MEMBER.MPASSWORD
     *
     * @mbg.generated
     */
    public void setMpassword(String mpassword) {
        this.mpassword = mpassword == null ? null : mpassword.trim();
    }
}